# Generated by Django 2.2.7 on 2019-11-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='create_date',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('comedy', 'Comedy'), ('tragedy', 'Tragedy'), ('drama', 'Drama'), ('adventure', 'Adventure'), ('history', 'History'), ("children's", "Children's"), ('crime', 'Crime'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('horror', 'Horror'), ('thriller', 'Thriller')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
