# Generated by Django 2.2.7 on 2019-11-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20191125_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('мужчина', 'Мужчина'), ('женщина', 'Женщина')], default='Выберете пол', max_length=7, verbose_name='Пол'),
        ),
    ]
